### ISSUE TITLE
Questions for display my own data in paraview

### ISSUE THREAD

**Issue by OMGTaylor0814** [mobigroup/ParaView-plugins#2]
Hi, i am a Phd student in OUC,i met a problem when i use Paraview python scripts.
I have a excel containing time steps (a total of 100s, one step per second). I want to display this data change when animating in Paraview. At first, I used "AnnotateTimeFilter" to display my customized data. However, I found that the built-in Format has fixed variables, so I can't recognize my data. I tried to read the excel file from the python script first, But I found that the Pandas library could not be used normally, so I wonder if you could provide a method to help me solve this problem? I also want to ask how to use the full python function?
Best Regards,
Junius Wang

**Comment by AlexeyPechnikov** [comment]
Hi Junius, that's not related to the project. You'd create 100 files like to ....00...., ....01...., ... and load them as timeseries.
